### PR TITLE
Create key from seed

### PR DESCRIPTION
**Pull request by TimDaub**
Based on #6 @vrde may wants to add description on what this is doing

image
image

### CODE REVIEW

**Comment by diminator** [comment]
also, maybe we should simple remove all bundles from the project?

**Comment by TimDaub** [comment]
> Based on #6

so this PR needs a rebase

**Comment by diminator** [comment]
> so this PR needs a rebase

will ya?

**Comment by TimDaub** [comment]
> will ya?

Done, had to `npm run build` during rebase.
No clue if it works. We should remove `/dist` from gitrepo IMO or automate build.

**Comment by kremalicious** [comment]
what's preventing us from merging this?

**Pull request merged**
