### PR TITLE
Issue #44 Multiple inputs for transfer transaction

### PR DESCRIPTION
**Pull request by ghost**
Old version
```
makeTransferTransaction(
    unspentTransaction,
    metadata,
    outputs,
    ...outputIndices
)
```

New version
```
makeTransferTransaction(
    unspentOutputs,
    outputs,
    metadata
)
```

`metadata` is now an optional parameter
`unspentOutputs` parameter is required to be an array with the following format
```
[
    { tx, output_index },
    { tx, output_index },
    ...
    { tx, output_index }
]
```
Where
`tx` is a complete transaction
`output_index` is index of unspent output fo given transaction

### CODE REVIEW

**Comment by TimDaub** [comment]
Hi @iredjee, thanks for this PR.

On first glance, I like the change of interface. Exactly what we needed.
To test this properly though, would you be so kind and test spending a transaction that includes inputs from two different transactions?

In a sense, similar to what you're doing here: https://github.com/bigchaindb/js-bigchaindb-driver/pull/98/files#diff-3624031141eaa84284612b7c47f3f42aR94

I just want to make sure that signing with two different private keys works.
I think testing this in the integration file is a good idea.

Thanks in advance already.

@ttmc Since @iredjee is from an organization that has potentially signed the CLA on bigchaindb/bigchaindb already, does he himself has to sign it again?
I don't want to post the organization's name in Github. Please ask me via email/slack.

**Comment by TimDaub** [comment]
@jernejpregelj I assigned you here to help @iredjee test this functionality.

**Comment by diminator** [comment]
very much inline with a wrapper I made in kyber: https://github.com/bigchaindb/kyber/blob/master/tutorials/utils/bigchaindb_utils.py#L30

**Comment by manolodewiner** [comment]
I created a new branch and a the pull request #120 in this repository including the commits made in this external repository iredjee/js-bigchaindb-driver/tree/transfer-multiple-inputs

**Comment by TimDaub** [comment]
I'm closing this, as we're handling it in updated PRs already.

**Pull request closed without merging**
