### PR TITLE
reduces development driver size to ~683k by removing vendor sourceMaps

### PR DESCRIPTION
**Pull request by dmvt**
screenshot from 2018-07-17 02-31-13

ref: https://github.com/bigchaindb/js-bigchaindb-driver/issues/221

### CODE REVIEW

**Comment by dmvt** [comment]
I'm not sure what's going on with the CI. Seems to be a connection problem to the bigchaindb instance. Here's what I get when running the tests locally:

```
TAP version 13
# transaction › test_cryptoconditions › Ed25519 condition encoding
ok 1 - transaction › test_cryptoconditions › Ed25519 condition encoding
# transaction › test_cryptoconditions › Sha256Condition fulfillment
ok 2 - transaction › test_cryptoconditions › Sha256Condition fulfillment
# transaction › test_cryptoconditions › Threshold condition encoding
ok 3 - transaction › test_cryptoconditions › Threshold condition encoding
# transaction › test_cryptoconditions › Fulfillment correctly formed
ok 4 - transaction › test_cryptoconditions › Fulfillment correctly formed
# transaction › test_cryptoconditions › CryptoConditions JSON load
ok 5 - transaction › test_cryptoconditions › CryptoConditions JSON load
# transaction › test_cryptoconditions › CryptoConditions JSON load
ok 6 - transaction › test_cryptoconditions › CryptoConditions JSON load
# constants › [anonymous]
ok 7 - constants › [anonymous]
# integration › test_integration › [anonymous]
ok 8 - integration › test_integration › [anonymous]
# integration › test_integration › Keypair is created
ok 9 - integration › test_integration › Keypair is created
# connection › test_connection › [anonymous]
ok 10 - connection › test_connection › [anonymous]
# connection › test_connection › Payload thrown at incorrect API_PATH
ok 11 - connection › test_connection › Payload thrown at incorrect API_PATH
# connection › test_connection › Generate API URLS
ok 12 - connection › test_connection › Generate API URLS
# connection › test_connection › Request with custom headers
ok 13 - connection › test_connection › Request with custom headers
# connection › test_connection › Get block for a block id
ok 14 - connection › test_connection › Get block for a block id
# connection › test_connection › Get transaction for a transaction id
ok 15 - connection › test_connection › Get transaction for a transaction id
# connection › test_connection › Get list of blocks for a transaction id
ok 16 - connection › test_connection › Get list of blocks for a transaction id
# connection › test_connection › Get list of transactions for an asset id
ok 17 - connection › test_connection › Get list of transactions for an asset id
# connection › test_connection › Get outputs for a public key and no spent flag
ok 18 - connection › test_connection › Get outputs for a public key and no spent flag
# connection › test_connection › Get outputs for a public key and spent=false
ok 19 - connection › test_connection › Get outputs for a public key and spent=false
# connection › test_connection › Get outputs for a public key and spent=true
ok 20 - connection › test_connection › Get outputs for a public key and spent=true
# connection › test_connection › Get votes for a block id
ok 21 - connection › test_connection › Get votes for a block id
# connection › test_connection › Get asset for text
ok 22 - connection › test_connection › Get asset for text
# connection › test_connection › Get metadata for text
ok 23 - connection › test_connection › Get metadata for text
# integration › test_integration › Content-Type cannot be set
ok 24 - integration › test_integration › Content-Type cannot be set
# integration › test_integration › Valid CREATE transaction using async
ok 25 - integration › test_integration › Valid CREATE transaction using async
# integration › test_integration › Valid CREATE transaction using sync
ok 26 - integration › test_integration › Valid CREATE transaction using sync
# integration › test_integration › Valid CREATE transaction
ok 27 - integration › test_integration › Valid CREATE transaction
# integration › test_integration › Search transaction containing an asset
ok 28 - integration › test_integration › Search transaction containing an asset
# integration › test_integration › Search blocks containing a transaction
ok 29 - integration › test_integration › Search blocks containing a transaction
# integration › test_integration › Valid TRANSFER transaction with single Ed25519 input
ok 30 - integration › test_integration › Valid TRANSFER transaction with single Ed25519 input
# integration › test_integration › Valid TRANSFER transaction with multiple Ed25519 inputs
ok 31 - integration › test_integration › Valid TRANSFER transaction with multiple Ed25519 inputs
# integration › test_integration › Search for spent outputs for a given public key
ok 32 - integration › test_integration › Search for spent outputs for a given public key
# integration › test_integration › Search for spent and unspent outputs of a given public key
ok 33 - integration › test_integration › Search for spent and unspent outputs of a given public key
# integration › test_integration › Search for unspent outputs for a given public key
ok 34 - integration › test_integration › Search for unspent outputs for a given public key
# integration › test_integration › Valid TRANSFER transaction with multiple Ed25519 inputs from different transactions
ok 35 - integration › test_integration › Valid TRANSFER transaction with multiple Ed25519 inputs from different transactions
# transaction › test_transaction › [anonymous]
ok 36 - transaction › test_transaction › [anonymous]
# transaction › test_transaction › Create valid output with default amount
ok 37 - transaction › test_transaction › Create valid output with default amount
# transaction › test_transaction › Create valid output with custom amount
ok 38 - transaction › test_transaction › Create valid output with custom amount
# transaction › test_transaction › Pass condition not based on public_keys to makeOutput
ok 39 - transaction › test_transaction › Pass condition not based on public_keys to makeOutput
# transaction › test_transaction › makeOutput throws TypeError with incorrect amount type
ok 40 - transaction › test_transaction › makeOutput throws TypeError with incorrect amount type
# transaction › test_transaction › Create TRANSFER transaction based on CREATE transaction
ok 41 - transaction › test_transaction › Create TRANSFER transaction based on CREATE transaction
# transaction › test_transaction › Create TRANSFER transaction based on TRANSFER transaction
ok 42 - transaction › test_transaction › Create TRANSFER transaction based on TRANSFER transaction
# integration › test_integration › Search for metadata
ok 43 - integration › test_integration › Search for metadata
# integration › test_integration › Search for an asset
ok 44 - integration › test_integration › Search for an asset

1..44
# tests 44
# pass 44
# fail 0

------------------------------|----------|----------|----------|----------|-------------------|
File                          |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------------------|----------|----------|----------|----------|-------------------|
All files                     |    85.61 |    69.15 |    84.38 |    85.27 |                   |
 src                          |    84.62 |    68.57 |    82.14 |    84.13 |                   |
  Ed25519Keypair.js           |      100 |       50 |      100 |      100 |                13 |
  baseRequest.js              |    73.33 |    64.86 |      100 |    72.41 |... 60,63,65,78,83 |
  connection.js               |      100 |    91.67 |      100 |      100 |                36 |
  format_text.js              |    39.13 |    26.67 |       50 |    36.36 |... 77,79,87,88,91 |
  request.js                  |    78.57 |       80 |    66.67 |    78.57 |          29,35,36 |
  sanitize.js                 |    73.91 |    59.09 |    66.67 |    73.68 |    13,14,18,20,31 |
  sha256Hash.js               |      100 |      100 |      100 |      100 |                   |
  stringify_as_query_param.js |    90.91 |    63.64 |      100 |       90 |                34 |
  transaction.js              |    97.65 |    78.79 |      100 |     97.5 |           148,171 |
 src/utils                    |       90 |    73.08 |      100 |       90 |                   |
  ccJsonLoad.js               |      100 |       90 |      100 |      100 |                28 |
  ccJsonify.js                |    80.77 |     62.5 |      100 |    80.77 |    13,14,55,56,57 |
------------------------------|----------|----------|----------|----------|-------------------|
```

**Comment by manolodewiner** [comment]
Please include #228 which is already in the master branch

**Comment by innoprenuer** [comment]
@dmvt There is a conflict in package.json due to PR #228. Please resolve the conflict. Then I will review and if all is okay and tests passes locally, I will merge.

**Comment by dmvt** [comment]
Updated @innoprenuer. I'm around all day if you encounter any issues.

**Comment by innoprenuer** [comment]
@dmvt Thanks. We will review it possibly by today :)

**Comment by dmvt** [comment]
@jernejpregelj updated

**Pull request merged**
