### PR TITLE
WIP: test-coverage-95

### PR DESCRIPTION
**Pull request by nemaniarjun**
This is a work in progress PR.

### CODE REVIEW

**Comment by manolodewiner** [comment]
Please include #228 which is already in the master branch

**Comment by nemaniarjun** [comment]
I wanted to ask @innoprenuer and the other devs, how should I got about testing https://github.com/bigchaindb/js-bigchaindb-driver/blob/master/src/sanitize.js ? The only exported function is `sanitize`, which calls `selectFromObject` with fixed params. To actually improve the line coverage in this file, we would need to be able to give different params to the functions. 

(One way is to use [`rewire`](https://github.com/jhnns/rewire) to import them to test them)
I have little experience with test design and need a little help how to go about this.

**Comment by nemaniarjun** [comment]
Also how do I arange the tests that I am adding, for example in ae53c3184d6a25b7e16c850c35d80d9b3874cbb6, is `test/test_format_text.js` fine or would you prefer a different path structure?

**Comment by innoprenuer** [comment]
@nemaniarjun Yes, `rewire` could be a good idea to test private (unexported) functions. So, go ahead with that. 
Regarding test path structure, as you might have seen, we follow - `test`/`<logical_unit_dir>`/`<test-file-name.js>` format. Try to use that if possible, but if you can't find any logical unit to put file in (e.g) connection, transaction etc. then place test files with proper logical name in `test/` folder itself. 

Do you have more queries?

**Comment by nemaniarjun** [comment]
Yes @innoprenuer, there is a redundant test at: https://github.com/bigchaindb/js-bigchaindb-driver/blob/aaad21895fcc19cd0465a0c099e880797271d4ac/test/transaction/test_cryptoconditions.js#L112 I think it was supposed to be a test for `ccJsonify` but there was some mistake. 

I tried to write a test for it as this: 
```
    const testJson = {
        type: 'threshold-sha-256',
        threshold: 1,
        subconditions: [{
            type: 'ed25519-sha-256',
            public_key: 'a'
        },
        {
            hash: 'a'
        }],
    }
    const cond = ccJsonLoad(testJson)
    const json = ccJsonify(cond)
    t.deepEqual(testJson, json)
```
But this gives me an error:
```
        UnsupportedTypeError {
          message: 'Type undefined is not supported',
        }
```

This seems like an error in the code, as the docs for both functions imply that 
`ccJsonify` converts `cypto-conditions` -> `json` and `ccJsonLoad` converts `json` -> `crypto-conditions`

In which case the above test should run, either I am missing something (highly likely as I am very very new to bigchaindb and to crypto in general.) or there is some error in the code.

**Comment by innoprenuer** [comment]
@nemaniarjun - couple of observations -

- `ccJsonify` and `ccJsonLoad` are inside `src/utils` and not directly `src`.
- ` const testJson = {
        type: 'threshold-sha-256',
        threshold: 1,
        subconditions: [{
            type: 'ed25519-sha-256',
            public_key: 'a' //MUST be base 58 encoded string. as it uses decode() from https://www.npmjs.com/package/bs58
        },
        {
            hash: 'a' //MUST be base 58 buffer string. as it uses encode() from https://www.npmjs.com/package/bs58
        }],
    }`

**Comment by nemaniarjun** [comment]
@innoprenuer The observations you added, don't change anything about my previous comment. The function ccJsonLoad automatically sets up everything (by that I mean, it automatically converts string to buffers / b58 encoded string.) 

The error I am facing stems from what could be a coding error. 
```
    if ('hash' in conditionJson) {
        const condition = new cc.Condition()
        condition.type = conditionJson.type_id
        condition.bitmask = conditionJson.bitmask
        condition.hash = Buffer.from(base58.decode(conditionJson.hash))
        condition.maxFulfillmentLength = parseInt(conditionJson.max_fulfillment_length, 10)
        return condition
    } 
```
The subcondition in the testJson does not have any `type_id`, thus the `type` is empty which gives out the error. 

I am gonna leave this as an observation and try to pick some other function to test, to reach my goal of 95%.

**Comment by nemaniarjun** [comment]
@innoprenuer The coverage is now at `94.96%` I guess that should be enough for this issue. :grin: 

Please review this as soon as possible :smile_cat:

**Comment by innoprenuer** [comment]
@nemaniarjun  sure. 94.96% is gladly acceptable 👍 We will review it and merge it if all is okay. Then I will release bounty reward. Later on, we will be happy to see you in our gitter channels https://gitter.im/bigchaindb/js-bigchaindb-driver
https://gitter.im/bigchaindb/bigchaindb

**Pull request merged**
